### ISSUE TITLE
Eavesarp frozen at start then stack dumps

### ISSUE THREAD

**Issue by kildonan5** [arch4ngel/eavesarp#1]
Cloned project to kali box and installed requirements. Started eavsarp with the command;
 **sudo ./eavesarp.py c -i eth0**

It hangs on the initialization screen

Capture interface: eth0
ARP resolution:    disabled
DNS resolution:    disabled
Requests analyzed: 0

And eventually stack traces;

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/sqlalchemy/engine/base.py", line 1244, in _execute_context
    cursor, statement, parameters, context
  File "/usr/local/lib/python3.7/dist-packages/sqlalchemy/engine/default.py", line 552, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: database is locked

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "./eavesarp.py", line 785, in <module>
    display_false=args.display_false)
  File "./eavesarp.py", line 147, in get_output_table
    transactions = get_transactions(db_session,order_by)
  File "/home/me/tools/eavesarp/Eavesarp/sql.py", line 252, in get_transactions
    .order_by(desc(Transaction.count)) \
  File "/usr/local/lib/python3.7/dist-packages/sqlalchemy/orm/query.py", line 3160, in all
    return list(self)
  File "/usr/local/lib/python3.7/dist-packages/sqlalchemy/orm/query.py", line 3316, in __iter__
    return self._execute_and_instances(context)
  File "/usr/local/lib/python3.7/dist-packages/sqlalchemy/orm/query.py", line 3341, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "/usr/local/lib/python3.7/dist-packages/sqlalchemy/engine/base.py", line 988, in execute
    return meth(self, multiparams, params)
  File "/usr/local/lib/python3.7/dist-packages/sqlalchemy/sql/elements.py", line 287, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/usr/local/lib/python3.7/dist-packages/sqlalchemy/engine/base.py", line 1107, in _execute_clauseelement
    distilled_params,
  File "/usr/local/lib/python3.7/dist-packages/sqlalchemy/engine/base.py", line 1248, in _execute_context
    e, statement, parameters, cursor, context
  File "/usr/local/lib/python3.7/dist-packages/sqlalchemy/engine/base.py", line 1466, in _handle_dbapi_exception
    util.raise_from_cause(sqlalchemy_exception, exc_info)
  File "/usr/local/lib/python3.7/dist-packages/sqlalchemy/util/compat.py", line 383, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/usr/local/lib/python3.7/dist-packages/sqlalchemy/util/compat.py", line 128, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.7/dist-packages/sqlalchemy/engine/base.py", line 1244, in _execute_context
    cursor, statement, parameters, context
  File "/usr/local/lib/python3.7/dist-packages/sqlalchemy/engine/default.py", line 552, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) database is locked
[SQL: SELECT "transaction".id AS transaction_id, "transaction".sender_ip_id AS transaction_sender_ip_id, "transaction".target_ip_id AS transaction_target_ip_id, "transaction".count AS transaction_count
FROM "transaction" ORDER BY "transaction".count DESC]
(Background on this error at: http://sqlalche.me/e/e3q8)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./eavesarp.py", line 902, in <module>
    if sniff_result:
NameError: name 'sniff_result' is not defined

**Comment by ImpostorKeanu** [comment]
Hmmm...interesting. When the requirements were installed, were they installed in context of root (sudo) and the following syntax was used?: `python3.7 -m pip install -r requirements.txt`. Also, we're sure that `eth0` is the proper interface?

**Comment by zoeified** [comment]
Running into a problem using this over an SSH Tunnel:
---
```
~/eavesarp$ sudo ./eavesarp.py --help
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused

(eavesarp.py:6652): Gdk-CRITICAL **: 18:08:31.390: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Traceback (most recent call last):
  File "./eavesarp.py", line 6, in <module>
    from Eavesarp.color import ColorProfiles
  File "/home/air/eavesarp/Eavesarp/color.py", line 3, in <module>
    import colored
ModuleNotFoundError: No module named 'colored'
```
