### ISSUE TITLE
Can´t make it work on Ubuntu 18.04.2 LTS

### ISSUE THREAD

**Issue by RomelSan** [arch4ngel/eavesarp#2]
Did install requirements.txt with Python 3.7.
on execution sudo python3.7 eavesarp.py c    i get:
```
 ___ ___ __  _____ ___ ___ ________
/ -_) _ `/ |/ / -_|_-</ _ `/ __/ _ \
\__/\_,_/|___/\__/___/\_,_/_/ / .__/
-----------------------------/ /---
[LISTEN CAREFULLY]          /_/

Capture interface: eth0
ARP resolution:    disabled
DNS resolution:    disabled
Requests analyzed: 0

- No accepted ARP requests captured
- If this is unexpected, check your whitelist/blacklist configuration
Exception ignored in: <function SuperSocket.__del__ at 0x7f0d30121bf8>
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/scapy/supersocket.py", line 123, in __del__
    self.close()
  File "/usr/local/lib/python3.7/dist-packages/scapy/arch/linux.py", line 481, in close
    set_promisc(self.ins, self.iface, 0)
  File "/usr/local/lib/python3.7/dist-packages/scapy/arch/linux.py", line 145, in set_promisc
    mreq = struct.pack("IHH8s", get_if_index(iff), PACKET_MR_PROMISC, 0, b"")
  File "/usr/local/lib/python3.7/dist-packages/scapy/arch/linux.py", line 360, in get_if_index
    return int(struct.unpack("I", get_if(iff, SIOCGIFINDEX)[16:20])[0])
  File "/usr/local/lib/python3.7/dist-packages/scapy/arch/common.py", line 50, in get_if
    ifreq = ioctl(sck, cmd, struct.pack("16s16x", iff.encode("utf8")))
OSError: [Errno 19] No such device
- Waiting for the sniffer process...done
- Done! Exiting
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "/usr/lib/python3.7/multiprocessing/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "/home/core/eavesarp/Eavesarp/eavesarp.py", line 96, in async_sniff
    target_lists)
  File "/home/core/eavesarp/Eavesarp/eavesarp.py", line 80, in do_sniff
    count=redraw_frequency
  File "/usr/local/lib/python3.7/dist-packages/scapy/sendrecv.py", line 836, in sniff
    *arg, **karg)] = iface
  File "/usr/local/lib/python3.7/dist-packages/scapy/arch/linux.py", line 456, in __init__
    set_promisc(self.ins, self.iface)
  File "/usr/local/lib/python3.7/dist-packages/scapy/arch/linux.py", line 145, in set_promisc
    mreq = struct.pack("IHH8s", get_if_index(iff), PACKET_MR_PROMISC, 0, b"")
  File "/usr/local/lib/python3.7/dist-packages/scapy/arch/linux.py", line 360, in get_if_index
    return int(struct.unpack("I", get_if(iff, SIOCGIFINDEX)[16:20])[0])
  File "/usr/local/lib/python3.7/dist-packages/scapy/arch/common.py", line 50, in get_if
    ifreq = ioctl(sck, cmd, struct.pack("16s16x", iff.encode("utf8")))
OSError: [Errno 19] No such device
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "eavesarp.py", line 799, in <module>
    packets = sniff_result.get()
  File "/usr/lib/python3.7/multiprocessing/pool.py", line 657, in get
    raise self._value
OSError: [Errno 19] No such device
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 63, in apport_excepthook
    from apport.fileutils import likely_packaged, get_recent_crashes
  File "/usr/lib/python3/dist-packages/apport/__init__.py", line 5, in <module>
    from apport.report import Report
  File "/usr/lib/python3/dist-packages/apport/report.py", line 30, in <module>
    import apport.fileutils
  File "/usr/lib/python3/dist-packages/apport/fileutils.py", line 23, in <module>
    from apport.packaging_impl import impl as packaging
  File "/usr/lib/python3/dist-packages/apport/packaging_impl.py", line 24, in <module>
    import apt
  File "/usr/lib/python3/dist-packages/apt/__init__.py", line 23, in <module>
    import apt_pkg
ModuleNotFoundError: No module named 'apt_pkg'

Original exception was:
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "/usr/lib/python3.7/multiprocessing/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "/home/core/eavesarp/Eavesarp/eavesarp.py", line 96, in async_sniff
    target_lists)
  File "/home/core/eavesarp/Eavesarp/eavesarp.py", line 80, in do_sniff
    count=redraw_frequency
  File "/usr/local/lib/python3.7/dist-packages/scapy/sendrecv.py", line 836, in sniff
    *arg, **karg)] = iface
  File "/usr/local/lib/python3.7/dist-packages/scapy/arch/linux.py", line 456, in __init__
    set_promisc(self.ins, self.iface)
  File "/usr/local/lib/python3.7/dist-packages/scapy/arch/linux.py", line 145, in set_promisc
    mreq = struct.pack("IHH8s", get_if_index(iff), PACKET_MR_PROMISC, 0, b"")
  File "/usr/local/lib/python3.7/dist-packages/scapy/arch/linux.py", line 360, in get_if_index
    return int(struct.unpack("I", get_if(iff, SIOCGIFINDEX)[16:20])[0])
  File "/usr/local/lib/python3.7/dist-packages/scapy/arch/common.py", line 50, in get_if
    ifreq = ioctl(sck, cmd, struct.pack("16s16x", iff.encode("utf8")))
OSError: [Errno 19] No such device
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "eavesarp.py", line 799, in <module>
    packets = sniff_result.get()
  File "/usr/lib/python3.7/multiprocessing/pool.py", line 657, in get
    raise self._value
OSError: [Errno 19] No such device

```

**Comment by RomelSan** [comment]
Removed all and installed everything as root.
It works.

**Comment by shaoxianxu** [comment]
Hello,

I have seen similar issues with scapy on ubuntu linux. could you please provide more details how you fix the issue?

**Comment by RomelSan** [comment]
> 
> 
> Hello,
> 
> I have seen similar issues with scapy on ubuntu linux. could you please provide more details how you fix the issue?

Follow the instructions "https://github.com/arch4ngel/eavesarp" but run every command with "sudo"
if you already installed without sudo then you must remove the installed packages.
Scapy always needs sudo. Unless you set group permissions for that.
If that does not work then take screenshot of the error and upload it here.
