### ISSUE TITLE
Stack trace when blacklist is a file

### ISSUE THREAD

**Issue by egypt** [arch4ngel/eavesarp#5]
With a command like this:
```
python3.7 eavesarp.py c -i eth0 --redraw-frequency 100 -bl bl.txt
```
I get a crash like this:
```
Traceback (most recent call last):                         
  File "eavesarp.py", line 216, in <module>                
    **{k:v for k,v in args.__dict__.items() if k.endswith('list')}
  File "/root/eavesarp/Eavesarp/lists.py", line 105, in initialize_lists
    blacklist = load_lists(blacklist or [])                
  File "/root/eavesarp/Eavesarp/lists.py", line 88, in load_lists
    if not Path(ival).exists():                            
NameError: name 'Path' is not defined                      
```

**Comment by ImpostorKeanu** [comment]
I should really do better regression testing.

Fixed in the following commits

5fee37942aac28dab58cb919e0ca40967f7c5764
67f3d42653320768093e6d2d3cc07f4951a0d5c1
